// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendPayNotify.proto

package io.grpc.fcw;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
