// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendPayNotify.proto

package io.grpc.fcw;

public final class SendPayNotifyProto {
  private SendPayNotifyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_SendAliPayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_SendAliPayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023SendPayNotify.proto\022\004grpc\"\'\n\021SendAliPa" +
      "yRequest\022\022\n\noutTradeNo\030\001 \001(\t\"\033\n\010Response" +
      "\022\017\n\007success\030\001 \001(\0102N\n\rSendPayNotify\022=\n\020Se" +
      "ndAliPayNotify\022\027.grpc.SendAliPayRequest\032" +
      "\016.grpc.Response(\001B#\n\013io.grpc.fcwB\022SendPa" +
      "yNotifyProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpc_SendAliPayRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_SendAliPayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_SendAliPayRequest_descriptor,
        new java.lang.String[] { "OutTradeNo", });
    internal_static_grpc_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_Response_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
