// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendPayNotify.proto

package io.grpc.fcw;

public interface SendAliPayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.SendAliPayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string outTradeNo = 1;</code>
   */
  java.lang.String getOutTradeNo();
  /**
   * <code>string outTradeNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getOutTradeNoBytes();
}
